[package]
name = "watchman"
version = "0.1.2"
authors = ["cezarmathe <me@cezarmathe.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotwatch = "0.4.5"
uslib = { path = "../uslib" }
